CopaFilmes/CopaFilmes.MVC/Controllers/FilmeController.cs
using CopaFilmes.Application.Interfaces;
using CopaFilmes.Application.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CopaFilmes.MVC.Controllers
{
    public class FilmeController : Controller
    {
        private readonly IFilmeAppService _filmeAppService;
        private readonly ICampeonatoAppService _campeonatoAppService;

        public FilmeController(IFilmeAppService filmeAppService, ICampeonatoAppService campeonatoAppService)
        {
            _filmeAppService = filmeAppService;
            _campeonatoAppService = campeonatoAppService;
        }

        // GET: Filme
        public ActionResult Index()
        {
            return View(_filmeAppService.ObterTodos().ToList());
        }

        [HttpPost]
        public ActionResult Index(List<FilmeViewModel> filmesSelecionados)
        {
            _campeonatoAppService.RelizarCampeonato(filmesSelecionados.Where(x => x.Selecionado));
            return View("ResultadoFinal", _campeonatoAppService.CampeonatoViewModel);
        }
    }
}

CopaFilmes/CopaFilmes.MVC/Views/Filme/Index.cshtml
@model List<CopaFilmes.Application.ViewModel.FilmeViewModel>
@Styles.Render("~/Content/filme")

@{
    ViewBag.Title = "Campeonato de filmes";
}

<br />
<div class="container">
    <div class="panel panel-default jumbotron text-center painel-principal">
        <p><label class="campeonato-filmes">CAMPEONATO DE FILMES</label></p>
        <p><label class="titulo-pagina">Fase de Seleção</label></p>
        <p><hr class="divisor" /></p>
        <p>
            <label class="mensagem-regras">
                Selecione 8 filmes que você deseja que entrem na competição e depois pressione o <br />
                botão Gerar Meu Campeonato para prosseguir.
            </label>
        </p>
    </div>
</div>
@using (Html.BeginForm("Index", "Filme", FormMethod.Post))
{
    <div class="container">
        <label style="color:white">Selecionados <br /><label id="totalChecados">0</label> de 8 filmes</label>
        <input type="submit" disabled="disabled" id="btnGerarCampeonato" class="btn pull-right btn-campeonato" value=" GERAR MEU CAMPEONATO " />
    </div>
    <br />

    for (int i = 0; i < Model.Count(); i++)
    {
        <div class="col-lg-3 col-md-4 col-sm-6">
            <div class="panel panel-default panel-footer">
                <p class="checkbox">
                    <input type="checkbox" id="@Model[i].Id" class="check-filme" style="margin-top:10px; margin-left: 8px" />&nbsp;&nbsp;&nbsp;
                    <label style="font-size: x-small;"><b>@Model[i].PrimaryTitle</b></label><br />&nbsp;&nbsp;&nbsp;
                    <label style="font-size: xx-small" class="text-muted">@Model[i].Year</label>
                </p>
            </div>
        </div>

        @Html.HiddenFor(m => m[i].Id)
        @Html.HiddenFor(m => m[i].PrimaryTitle)
        @Html.HiddenFor(m => m[i].AverageRating)
        @Html.HiddenFor(m => m[i].Year)
        @Html.HiddenFor(m => m[i].Selecionado, new { @id = Model[i].Id })
    }
}

@section Scripts {
    @Scripts.Render("~/bundles/scriptsFilme")
}

CopaFilmes/CopaFilmes.MVC/Views/Filme/ResultadoFinal.cshtml
@model CopaFilmes.Application.ViewModel.CampeonatoViewModel
@Styles.Render("~/Content/filme")

@{
    ViewBag.Title = "Campeonato de filmes";
}

<br />
<div class="panel panel-default jumbotron text-center painel-principal">
    <p><label class="campeonato-filmes">CAMPEONATO DE FILMES</label></p>
    <p><label class="titulo-pagina">Resultao Final</label></p>
    <p><hr class="divisor" /></p>
    <p>
        <label class="mensagem-regras">
            Veja o resultado final do Campeonato de filmes de forma simples e rapida.
        </label>
    </p>
</div>

<br />

<div class="container">
    <div class="row">
        <label class="posicao-final">1º</label>
        <label class="filme-vencedor">@Model.Campeao.PrimaryTitle</label>
    </div>
    <br />
    <div class="row">
        <label class="posicao-final">2º</label>
        <label class="filme-vencedor">@Model.ViceCampeao.PrimaryTitle</label>
    </div>
</div>

CopaFilmes/CopaFilmes.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Copa Filmes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color: dimgrey">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Campeonato de Filmes", "Index", "Filme", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>